// GENERATED by scripts/prep_assets.py — do not edit by hand.
// Every size here was measured off the file on disk.

import type { Asset, Clip } from "./assets.ts";

export const ASSETS: Asset[] = [
 {
  "slug": "p12-1",
  "file": "img/p12-1.webp",
  "kind": "render",
  "model": 12,
  "w": 2400,
  "h": 1797,
  "ar": 2.0571,
  "bbox": [
   0.1174,
   0.3094,
   0.8833,
   0.8067
  ],
  "transparent": true
 },
 {
  "slug": "p12-2",
  "file": "img/p12-2.webp",
  "kind": "plan",
  "model": 12,
  "w": 4088,
  "h": 3072,
  "ar": 0.6511,
  "bbox": [
   0.3175,
   0.126,
   0.695,
   0.8975
  ],
  "transparent": true
 },
 {
  "slug": "p12-3",
  "file": "img/p12-3.webp",
  "kind": "render",
  "model": 12,
  "w": 2400,
  "h": 1799,
  "ar": 1.38,
  "bbox": [
   0.1721,
   0.2081,
   0.8369,
   0.8508
  ],
  "transparent": true
 },
 {
  "slug": "p12-4",
  "file": "img/p12-4.webp",
  "kind": "render",
  "model": 12,
  "w": 1500,
  "h": 1124,
  "ar": 1.3804,
  "bbox": [
   0.172,
   0.2082,
   0.8373,
   0.8514
  ],
  "transparent": true
 },
 {
  "slug": "p12-5",
  "file": "img/p12-5.webp",
  "kind": "panel",
  "model": 12,
  "w": 2400,
  "h": 1799,
  "ar": 3.28,
  "bbox": [
   0.3037,
   0.4093,
   0.6936,
   0.5679
  ],
  "transparent": true
 },
 {
  "slug": "p12-6",
  "file": "img/p12-6.webp",
  "kind": "render",
  "model": 12,
  "w": 2400,
  "h": 1799,
  "ar": 1.4004,
  "bbox": [
   0.175,
   0.2638,
   0.8435,
   0.9007
  ],
  "transparent": true
 },
 {
  "slug": "p12-7",
  "file": "img/p12-7.webp",
  "kind": "render",
  "model": 12,
  "w": 2400,
  "h": 1798,
  "ar": 2.0548,
  "bbox": [
   0.135,
   0.3025,
   0.8621,
   0.7748
  ],
  "transparent": true
 },
 {
  "slug": "p16-1",
  "file": "img/p16-1.webp",
  "kind": "render",
  "model": 16,
  "w": 2400,
  "h": 1797,
  "ar": 2.1605,
  "bbox": [
   0.1028,
   0.2964,
   0.9182,
   0.8005
  ],
  "transparent": true
 },
 {
  "slug": "p16-2",
  "file": "img/p16-2.webp",
  "kind": "render",
  "model": 16,
  "w": 2400,
  "h": 1799,
  "ar": 1.4756,
  "bbox": [
   0.146,
   0.1886,
   0.8875,
   0.859
  ],
  "transparent": true
 },
 {
  "slug": "p16-3",
  "file": "img/p16-3.webp",
  "kind": "render",
  "model": 16,
  "w": 2400,
  "h": 1799,
  "ar": 1.4589,
  "bbox": [
   0.1355,
   0.172,
   0.8704,
   0.844
  ],
  "transparent": true
 },
 {
  "slug": "p16-4",
  "file": "img/p16-4.webp",
  "kind": "plan",
  "model": 16,
  "w": 4087,
  "h": 3072,
  "ar": 0.838,
  "bbox": [
   0.2618,
   0.1097,
   0.7477,
   0.8812
  ],
  "transparent": true
 },
 {
  "slug": "p16-5",
  "file": "img/p16-5.webp",
  "kind": "panel",
  "model": 16,
  "w": 2400,
  "h": 1803,
  "ar": 4.2404,
  "bbox": [
   0.247,
   0.4079,
   0.7479,
   0.5651
  ],
  "transparent": true
 },
 {
  "slug": "p16-6",
  "file": "img/p16-6.webp",
  "kind": "render",
  "model": 16,
  "w": 2400,
  "h": 1799,
  "ar": 2.1779,
  "bbox": [
   0.1216,
   0.3088,
   0.8979,
   0.7844
  ],
  "transparent": true
 },
 {
  "slug": "p16-7",
  "file": "img/p16-7.webp",
  "kind": "photo",
  "model": 16,
  "w": 2048,
  "h": 1456,
  "ar": 1.4066,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "p16-8",
  "file": "img/p16-8.webp",
  "kind": "photo",
  "model": 16,
  "w": 1014,
  "h": 679,
  "ar": 1.4934,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "p22-1",
  "file": "img/p22-1.webp",
  "kind": "render",
  "model": 22,
  "w": 2400,
  "h": 1799,
  "ar": 2.6618,
  "bbox": [
   0.0723,
   0.2518,
   0.9263,
   0.6798
  ],
  "transparent": true
 },
 {
  "slug": "p22-10",
  "file": "img/p22-10.webp",
  "kind": "photo",
  "model": 22,
  "w": 1008,
  "h": 669,
  "ar": 1.5067,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "p22-11",
  "file": "img/p22-11.webp",
  "kind": "photo",
  "model": 22,
  "w": 1014,
  "h": 674,
  "ar": 1.5045,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "p22-2",
  "file": "img/p22-2.webp",
  "kind": "plan",
  "model": 22,
  "w": 4076,
  "h": 3072,
  "ar": 1.0736,
  "bbox": [
   0.1914,
   0.1195,
   0.8108,
   0.8851
  ],
  "transparent": true
 },
 {
  "slug": "p22-3",
  "file": "img/p22-3.webp",
  "kind": "render",
  "model": 22,
  "w": 2400,
  "h": 1795,
  "ar": 2.2598,
  "bbox": [
   0.0764,
   0.3195,
   0.9292,
   0.8241
  ],
  "transparent": true
 },
 {
  "slug": "p22-4",
  "file": "img/p22-4.webp",
  "kind": "render",
  "model": 22,
  "w": 2400,
  "h": 1799,
  "ar": 1.5339,
  "bbox": [
   0.0908,
   0.1902,
   0.905,
   0.8984
  ],
  "transparent": true
 },
 {
  "slug": "p22-5",
  "file": "img/p22-5.webp",
  "kind": "panel",
  "model": 22,
  "w": 2400,
  "h": 950,
  "ar": 5.1831,
  "bbox": [
   0.1025,
   0.2885,
   0.8855,
   0.6702
  ],
  "transparent": true
 },
 {
  "slug": "p22-6",
  "file": "img/p22-6.webp",
  "kind": "render",
  "model": 22,
  "w": 2400,
  "h": 1791,
  "ar": 2.3121,
  "bbox": [
   0.1023,
   0.2929,
   0.917,
   0.7651
  ],
  "transparent": true
 },
 {
  "slug": "p22-7",
  "file": "img/p22-7.webp",
  "kind": "panel",
  "model": 22,
  "w": 2400,
  "h": 1800,
  "ar": 5.373,
  "bbox": [
   0.1792,
   0.4079,
   0.8193,
   0.5667
  ],
  "transparent": true
 },
 {
  "slug": "p22-8",
  "file": "img/p22-8.webp",
  "kind": "panel",
  "model": 22,
  "w": 2400,
  "h": 952,
  "ar": 5.3515,
  "bbox": [
   0.0989,
   0.29,
   0.8818,
   0.6589
  ],
  "transparent": true
 },
 {
  "slug": "p22-9",
  "file": "img/p22-9.webp",
  "kind": "render",
  "model": 22,
  "w": 2400,
  "h": 1799,
  "ar": 1.5464,
  "bbox": [
   0.0972,
   0.1951,
   0.9172,
   0.9026
  ],
  "transparent": true
 },
 {
  "slug": "p32-1",
  "file": "img/p32-1.webp",
  "kind": "plan",
  "model": 32,
  "w": 4096,
  "h": 3072,
  "ar": 1.5413,
  "bbox": [
   0.0493,
   0.1133,
   0.9468,
   0.8896
  ],
  "transparent": true
 },
 {
  "slug": "p32-2",
  "file": "img/p32-2.webp",
  "kind": "render",
  "model": 32,
  "w": 2400,
  "h": 1792,
  "ar": 2.4129,
  "bbox": [
   0.0371,
   0.2867,
   0.9241,
   0.779
  ],
  "transparent": true
 },
 {
  "slug": "p32-3",
  "file": "img/p32-3.webp",
  "kind": "render",
  "model": 32,
  "w": 2400,
  "h": 1799,
  "ar": 1.6337,
  "bbox": [
   0.0208,
   0.1277,
   0.9622,
   0.8964
  ],
  "transparent": true
 },
 {
  "slug": "p32-4",
  "file": "img/p32-4.webp",
  "kind": "render",
  "model": 32,
  "w": 2048,
  "h": 1532,
  "ar": 2.4275,
  "bbox": [
   0.0654,
   0.2996,
   0.9722,
   0.799
  ],
  "transparent": true
 },
 {
  "slug": "p32-5",
  "file": "img/p32-5.webp",
  "kind": "panel",
  "model": 32,
  "w": 2400,
  "h": 1800,
  "ar": 7.5178,
  "bbox": [
   0.0415,
   0.4049,
   0.9592,
   0.5677
  ],
  "transparent": true
 },
 {
  "slug": "p32-6",
  "file": "img/p32-6.webp",
  "kind": "render",
  "model": 32,
  "w": 2400,
  "h": 1799,
  "ar": 1.647,
  "bbox": [
   0.0259,
   0.1329,
   0.9753,
   0.902
  ],
  "transparent": true
 },
 {
  "slug": "p32-7",
  "file": "img/p32-7.webp",
  "kind": "photo",
  "model": 32,
  "w": 974,
  "h": 645,
  "ar": 1.5101,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 }
];

export const CLIPS: Clip[] = [
 {
  "slug": "of-02-desk-tracking",
  "file": "clip/of-02-desk-tracking.mp4",
  "w": 1280,
  "h": 720,
  "ar": 1.7778,
  "dur": 1.23,
  "kind": "official",
  "what": "engineer at the desk, guitarist behind"
 },
 {
  "slug": "of-03-plan-reveal",
  "file": "clip/of-03-plan-reveal.mp4",
  "w": 1280,
  "h": 720,
  "ar": 1.7778,
  "dur": 1.9,
  "kind": "official",
  "what": "the 32 rotating into its top-down plan"
 },
 {
  "slug": "of-04-outdoor-band",
  "file": "clip/of-04-outdoor-band.mp4",
  "w": 704,
  "h": 720,
  "ar": 0.9778,
  "dur": 2.3,
  "kind": "official",
  "what": "outdoor band, bass and guitar"
 },
 {
  "slug": "of-05-console-hands",
  "file": "clip/of-05-console-hands.mp4",
  "w": 1280,
  "h": 720,
  "ar": 1.7778,
  "dur": 2.7,
  "kind": "official",
  "what": "hands working the channel strips"
 },
 {
  "slug": "of-06-studio-seat",
  "file": "clip/of-06-studio-seat.mp4",
  "w": 1280,
  "h": 720,
  "ar": 1.7778,
  "dur": 0.73,
  "kind": "official",
  "what": "studio seat, headphones and laptop"
 }
];

/** B-roll slugs not yet on disk. shots.ts falls back for these. */
export const MISSING_BROLL: string[] = ["broll-01-live-foh", "broll-02-community-hall", "broll-03-project-studio", "broll-04-rehearsal-room"];

/** Mean luminance of each named region, 0..1, measured on the plan. */
export const REGION_LUM: Record<string, number> = {
 "connectors": 0.2905,
 "phantom": 0.3919,
 "gain": 0.3545,
 "padHpf": 0.3443,
 "comp": 0.3386,
 "eq": 0.3808,
 "midSweep": 0.3854,
 "aux": 0.2802,
 "fxSend": 0.2744,
 "routing": 0.3141,
 "faders": 0.2404,
 "hiZ": 0.2737,
 "usbC": 0.2581,
 "qr": 0.334,
 "usbReturn": 0.2688,
 "outJacks": 0.4729,
 "outXlr": 0.4369,
 "monitor": 0.5579,
 "talkback": 0.2096,
 "lexicon": 0.4466,
 "meter": 0.2506,
 "auxMaster": 0.3642,
 "masterFader": 0.4687,
 "master": 0.3679
};
