"""Builds public/img, public/soft, public/amb and src/assets.generated.ts.

For every image in scripts/catalog.py:
  img/   the picture itself, long side capped at 3840 px (photos, JPEG q92) or
         kept as a PNG where it carries transparency (renders, elevations)
  soft/  a defocused copy at 960 px — crossfaded over the sharp one for the
         rack-focus pulls, so no shot ever runs filter: blur() at 4K
  amb/   a heavily blurred, darkened 640 px cover copy — the ambient ground a
         complete picture sits on when its shape is not the frame's

Every size is measured off the file, including the CONTENT box of transparent
pictures (renders occupy different fractions of their canvases), the mean
luminance (so the overlay can decide how much ground it needs) and the
dominant hue (for the glow behind a render).
"""
import json, os, re, sys, hashlib
import numpy as np
from PIL import Image, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from catalog import C, SERIES  # noqa: E402

ROOT = "/home/user"
PUB = os.path.join(HERE, "..", "public")
for d in ("img", "soft", "amb"):
    os.makedirs(os.path.join(PUB, d), exist_ok=True)

def slugify(product, kind, fname, seen):
    base = re.sub(r"[^a-z0-9]+", "-", fname.lower().replace("soundcraft ", "").rsplit(".", 1)[0]).strip("-")
    ext = fname.rsplit(".", 1)[1].lower()
    s = f"{kind}-{base}-{ext}"
    while s in seen:
        s += "x"
    seen.add(s)
    return s

out = []
seen = set()
for e in C:
    repo, fname, product, kind = e[:4]
    note = e[4] if len(e) > 4 else ""
    src = os.path.join(ROOT, repo, fname)
    im = Image.open(src)
    im.load()
    has_alpha = kind not in ("life", "feature", "banner") and im.mode in ("RGBA", "LA", "P") and np.array(im.convert("RGBA"))[..., 3].min() < 250
    im = im.convert("RGBA" if has_alpha else "RGB")
    W0, H0 = im.size
    cap = 4096 if kind == "plan" else (3000 if has_alpha else 3840)
    if max(W0, H0) > cap:
        k = cap / max(W0, H0)
        im = im.resize((round(W0 * k), round(H0 * k)), Image.LANCZOS)
    W, H = im.size
    slug = slugify(product, kind, fname, seen)
    ext = "png" if has_alpha else "jpg"
    path = f"img/{slug}.{ext}"
    if has_alpha:
        im.save(os.path.join(PUB, path), optimize=True)
        a = np.array(im)[..., 3]
        ys, xs = np.where(a > 24)
        bbox = [xs.min() / W, ys.min() / H, (xs.max() + 1) / W, (ys.max() + 1) / H]
        rgb = np.array(im)[..., :3][a > 128]
    else:
        im.save(os.path.join(PUB, path), quality=92, subsampling=0, optimize=True)
        bbox = [0, 0, 1, 1]
        rgb = np.array(im).reshape(-1, 3)
    lum = float((rgb @ np.array([0.2126, 0.7152, 0.0722])).mean() / 255) if len(rgb) else 0.2
    # defocused copy for rack focus
    sk = 960 / max(W, H)
    soft = im.resize((max(1, round(W * sk)), max(1, round(H * sk))), Image.LANCZOS).filter(ImageFilter.GaussianBlur(7))
    spath = f"soft/{slug}.{ext}"
    soft.save(os.path.join(PUB, spath), **({} if has_alpha else {"quality": 85}))
    # ambient ground: cover-filled, blurred hard, darkened
    ak = 640 / max(W, H)
    amb = im.convert("RGB") if not has_alpha else Image.alpha_composite(Image.new("RGBA", im.size, (10, 11, 14, 255)), im).convert("RGB")
    amb = amb.resize((max(1, round(W * ak)), max(1, round(H * ak))), Image.LANCZOS).filter(ImageFilter.GaussianBlur(26))
    amb = Image.fromarray((np.array(amb).astype(np.float32) * 0.55).astype(np.uint8))
    apath = f"amb/{slug}.jpg"
    amb.save(os.path.join(PUB, apath), quality=80)
    out.append(dict(
        slug=slug, file=path, soft=spath, amb=apath, w=W, h=H, ar=round(W / H, 4),
        transparent=bool(has_alpha), bbox=[round(v, 4) for v in bbox], lum=round(lum, 3),
        product=product, series=SERIES[product], kind=kind, note=note, src=f"{repo}/{fname}",
    ))
    print(f"{slug:48s} {W}x{H} {kind:7s} {product}")

ts = [
    "// GENERATED by scripts/prep_assets.py from scripts/catalog.py — do not edit by hand.",
    "// Every size, content box and luminance is measured off the file.",
    "export type Asset = {",
    "  slug: string; file: string; soft: string; amb: string;",
    "  w: number; h: number; ar: number; transparent: boolean;",
    "  bbox: [number, number, number, number]; lum: number;",
    "  product: string; series: 'p12' | 'p16' | 'p22' | 'p32' | 'all'; kind: string; note: string; src: string;",
    "};",
    f"export const ASSETS: Asset[] = {json.dumps(out, indent=1)};",
    "",
]
open(os.path.join(HERE, "..", "src", "assets.generated.ts"), "w").write("\n".join(ts))
print(len(out), "assets")
