# (heading as spoken, additional narration) per caption window, in plan order.
# Each window's word count sits within one word of (window seconds × 152 / 60).
REEL = [
 ("Signature Plus Series.", "Soundcraft's next generation of analog mixing consoles, built for the real rooms where music happens."),
 ("Perfected performances.", "From a café duo to a festival stage, this is exactly where every great mix begins."),
 ("Four sizes. One desk.", "Every model shares the same master section, the same tools, and the same signature sound."),
 ("Twelve, sixteen, twenty-two, thirty-two.", "Choose the input count your busiest night needs, and absolutely nothing else about the desk changes."),
 ("Ghost mic preamps.", "Every mono channel opens on Soundcraft's legendary Ghost preamp, clean, open and very quiet."),
 ("Six to sixty-five decibels of gain.", "Enough for a quiet ribbon microphone, with no hiss at all."),
 ("Sapphyre EQ.", "Three bands, with a mid you sweep by hand, from one-fifty hertz to three kilohertz."),
 ("dbx compression.", "Built right into every mono channel, so loud words and hard notes stop jumping out."),
 ("One knob. One switch.", "The OverEasy curve leans in gently, so you can stop riding the faders."),
 ("Lexicon effects.", "Studio-grade reverbs and delays, built right into the desk, with no outboard rack to carry."),
 ("Thirty-two presets. Tap tempo.", "Two banks of sixteen, store your favourite, and tap the delay in time."),
 ("Four aux sends.", "On every channel, each one switchable pre or post fade, for monitor and effects mixes."),
 ("Talkback to any output.", "It has its own XLR and preamp, routed wherever the crew needs it."),
 ("Dual metering.", "Analog dBu beside digital dBFS, so the desk and the recording always agree on your levels."),
 ("USB-C. Four in, four out.", "Multitrack recording and playback straight from the console to your laptop, with no interface."),
 ("Record and stream.", "Capture the whole show while you mix it, and send that very same mix out live."),
 ("Live stages.", "From a packed club on a Friday to a festival crowd at dusk, front of house stays in control."),
 ("Galas and events.", "Ballrooms, weddings and receptions, where every single speech, toast and song has to land cleanly for the room."),
 ("Conferences and studios.", "Panels that stay intelligible to the back row, and home studios that track straight to a laptop."),
 ("Schools and broadcast.", "Band classrooms where students learn, radio booths and live streams, all running smoothly on one familiar analog surface."),
 ("Every performance.", "Worship, theatre, rehearsal and podcast, one family of consoles covers them all, from soundcheck to the very last song."),
 ("Colour-coded layout.", "Every knob is coded by function, so in a dark venue your hand finds the row fast."),
 ("Long-throw faders.", "A rugged metal chassis and smooth faders, built to work night after night, and gig after gig."),
 ("One family.", "Soundcraft Signature Plus: twelve, sixteen, twenty-two and thirty-two. Now, which one is yours?"),
 ("", "Shivansh Electronics is the Exclusive Partner of the Soundcraft Signature Plus Mixer Series. Follow us."),
]
VIDEO = [
 ("Signature Plus Series.", "Soundcraft's next generation of professional analog mixing consoles, designed for the clubs, churches, schools and stages where real performances happen, night after night."),
 ("Perfected performances.", "Warm, detailed analog sound, a workflow you already know, and the tools modern shows demand, all on one surface, for ten people or ten thousand."),
 ("Four sizes. One desk.", "The Signature Plus series comes in four sizes, and every one is the same desk."),
 ("Twelve, sixteen, twenty-two, thirty-two.", "The twelve is not a cut-down console, it simply has fewer channels to suit smaller rooms."),
 ("The same master section.", "Same preamps, same EQ, same compressor, same Lexicon effects, same metering on every model."),
 ("Ghost mic preamps.", "Every mono channel opens on a Soundcraft Ghost preamp, prized for clarity."),
 ("Six to sixty-five decibels of gain.", "A quiet ribbon comes up without hiss."),
 ("Pad and a hundred hertz filter.", "Tame the kick drum, and cut stage rumble early."),
 ("Sapphyre EQ.", "Every mono channel gets Soundcraft's musical three-band Sapphyre EQ, with shelves set at sixty hertz and twelve kilohertz."),
 ("Swept mid, one-fifty hertz to three kilohertz.", "Sweep it by hand to find and remove the ring in any room."),
 ("dbx compression.", "Now the part that usually lives in an outboard rack, a genuine dbx compressor, built right into the desk."),
 ("On every mono channel.", "Not on two channels, not on a single bus, but on every mono input you have."),
 ("One knob. One switch.", "The OverEasy curve arrives gradually, so loud words and hard notes stop jumping out of the mix."),
 ("Lexicon effects.", "Reverb and delay come from Lexicon, the name studios have trusted, built right into the desk, with halls, plates, chambers, rooms and spring."),
 ("Thirty-two presets. Tap tempo.", "Two banks of sixteen, store your favourite, tap the delay in time with the band, from the surface or a footswitch."),
 ("Four aux sends.", "Every channel carries four aux sends, each switchable pre or post fade, for monitors and effects."),
 ("Talkback to any output.", "Talkback has its own XLR and preamp, reaching the stage or any output you choose."),
 ("Dual metering.", "Analog dBu beside digital dBFS, so the analog desk and your recording never disagree about level."),
 ("Mix to aux.", "The main mix can go to an aux, the fastest way to build an in-ear feed."),
 ("USB-C. Four in, four out.", "On the back, a USB-C socket sends four channels each way to your computer."),
 ("Record and stream.", "Record the show while you mix it, or stream it live, with no interface needed."),
 ("Hi-Z. No DI box.", "Dedicated Hi-Z inputs take guitar or bass straight in, so the stage stays tidy."),
 ("Signature Plus Twelve.", "Six mono channels, twelve inputs in total."),
 ("Six mono, twelve inputs.", "Perfect for podcasts, duos, and chapels."),
 ("Signature Plus Sixteen.", "Ten mono channels, sixteen inputs in total."),
 ("Ten mono, sixteen inputs.", "A full band with a laptop."),
 ("Signature Plus Twenty-two.", "Fourteen mono channels, twenty-two inputs in total."),
 ("Fourteen mono, twenty-two inputs.", "A full band, plus monitor mixes."),
 ("Signature Plus Thirty-two.", "Twenty-four mono channels, thirty-two inputs in total."),
 ("Twenty-four mono, thirty-two inputs.", "For bigger rooms and bigger shows."),
 ("Live stages.", "From a packed club to a festival crowd at dusk, front of house stays calm and in control."),
 ("Galas and events.", "Ballrooms, weddings and receptions, where every speech and every song has to land cleanly for the whole room."),
 ("Studios.", "Home studios and production rooms, tracking straight to a laptop over USB-C, with no separate audio interface in the chain."),
 ("Rehearsal rooms.", "A full band tracking together, with every microphone on its own channel and headphone mixes from the aux sends."),
 ("Every performance.", "Worship, theatre, conference, classroom, radio and live stream, one family of consoles covers them all, from soundcheck to encore."),
 ("QR code manuals.", "A QR code on the surface opens the manual and training videos on your phone."),
 ("Colour-coded layout.", "Every knob is colour-coded by function, so in the dark your hand finds it first."),
 ("Metal chassis.", "A rugged metal chassis built to survive the road, the van and the load-in, night after night."),
 ("Long-throw faders.", "Smooth long-throw faders give you fine, precise control of every vocal and instrument, show after show."),
 ("Which one is yours?", "Count the inputs you plug in on your busiest night, then add four for growth, and choose."),
 ("One family.", "Soundcraft Signature Plus. Twelve, sixteen, twenty-two, thirty-two. Professional analog mixing, reimagined for the way you perform, record and stream."),
 ("", "Shivansh Electronics is the Exclusive Partner of the Soundcraft Signature Plus Mixer Series. Visit our website, call the numbers on screen, and follow us today."),
]
