// GENERATED by scripts/prep_assets.py — do not edit by hand.
// Every size here was measured off the file on disk.

import type { Asset, Clip } from "./assets.ts";

export const ASSETS: Asset[] = [
 {
  "slug": "p12-1",
  "file": "img/p12-1.webp",
  "kind": "render",
  "model": 12,
  "w": 2200,
  "h": 1647,
  "ar": 2.0574,
  "bbox": [
   0.1174,
   0.3094,
   0.8833,
   0.8067
  ],
  "transparent": true
 },
 {
  "slug": "p12-2",
  "file": "img/p12-2.webp",
  "kind": "plan",
  "model": 12,
  "w": 4088,
  "h": 3072,
  "ar": 0.6511,
  "bbox": [
   0.3175,
   0.126,
   0.695,
   0.8975
  ],
  "transparent": true
 },
 {
  "slug": "p12-3",
  "file": "img/p12-3.webp",
  "kind": "render",
  "model": 12,
  "w": 2200,
  "h": 1649,
  "ar": 1.3801,
  "bbox": [
   0.1721,
   0.2081,
   0.8369,
   0.8508
  ],
  "transparent": true
 },
 {
  "slug": "p12-4",
  "file": "img/p12-4.webp",
  "kind": "render",
  "model": 12,
  "w": 1500,
  "h": 1124,
  "ar": 1.3804,
  "bbox": [
   0.172,
   0.2082,
   0.8373,
   0.8514
  ],
  "transparent": true
 },
 {
  "slug": "p12-5",
  "file": "img/p12-5.webp",
  "kind": "panel",
  "model": 12,
  "w": 2200,
  "h": 1649,
  "ar": 3.2802,
  "bbox": [
   0.3037,
   0.4093,
   0.6936,
   0.5679
  ],
  "transparent": true
 },
 {
  "slug": "p12-6",
  "file": "img/p12-6.webp",
  "kind": "render",
  "model": 12,
  "w": 2200,
  "h": 1649,
  "ar": 1.4004,
  "bbox": [
   0.175,
   0.2638,
   0.8435,
   0.9007
  ],
  "transparent": true
 },
 {
  "slug": "p12-7",
  "file": "img/p12-7.webp",
  "kind": "render",
  "model": 12,
  "w": 2200,
  "h": 1648,
  "ar": 2.055,
  "bbox": [
   0.135,
   0.3025,
   0.8621,
   0.7748
  ],
  "transparent": true
 },
 {
  "slug": "p16-1",
  "file": "img/p16-1.webp",
  "kind": "render",
  "model": 16,
  "w": 2200,
  "h": 1647,
  "ar": 2.1608,
  "bbox": [
   0.1028,
   0.2964,
   0.9182,
   0.8005
  ],
  "transparent": true
 },
 {
  "slug": "p16-2",
  "file": "img/p16-2.webp",
  "kind": "render",
  "model": 16,
  "w": 2200,
  "h": 1649,
  "ar": 1.4756,
  "bbox": [
   0.146,
   0.1886,
   0.8875,
   0.859
  ],
  "transparent": true
 },
 {
  "slug": "p16-3",
  "file": "img/p16-3.webp",
  "kind": "render",
  "model": 16,
  "w": 2200,
  "h": 1649,
  "ar": 1.459,
  "bbox": [
   0.1355,
   0.172,
   0.8704,
   0.844
  ],
  "transparent": true
 },
 {
  "slug": "p16-4",
  "file": "img/p16-4.webp",
  "kind": "plan",
  "model": 16,
  "w": 4087,
  "h": 3072,
  "ar": 0.838,
  "bbox": [
   0.2618,
   0.1097,
   0.7477,
   0.8812
  ],
  "transparent": true
 },
 {
  "slug": "p16-5",
  "file": "img/p16-5.webp",
  "kind": "panel",
  "model": 16,
  "w": 2200,
  "h": 1653,
  "ar": 4.2397,
  "bbox": [
   0.247,
   0.4079,
   0.7479,
   0.5651
  ],
  "transparent": true
 },
 {
  "slug": "p16-6",
  "file": "img/p16-6.webp",
  "kind": "render",
  "model": 16,
  "w": 2200,
  "h": 1649,
  "ar": 2.178,
  "bbox": [
   0.1216,
   0.3088,
   0.8979,
   0.7844
  ],
  "transparent": true
 },
 {
  "slug": "p16-7",
  "file": "img/p16-7.webp",
  "kind": "photo",
  "model": 16,
  "w": 2048,
  "h": 1456,
  "ar": 1.4066,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "p16-8",
  "file": "img/p16-8.webp",
  "kind": "photo",
  "model": 16,
  "w": 1014,
  "h": 679,
  "ar": 1.4934,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "p22-1",
  "file": "img/p22-1.webp",
  "kind": "render",
  "model": 22,
  "w": 2200,
  "h": 1649,
  "ar": 2.662,
  "bbox": [
   0.0723,
   0.2518,
   0.9263,
   0.6798
  ],
  "transparent": true
 },
 {
  "slug": "p22-10",
  "file": "img/p22-10.webp",
  "kind": "photo",
  "model": 22,
  "w": 1008,
  "h": 669,
  "ar": 1.5067,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "p22-11",
  "file": "img/p22-11.webp",
  "kind": "photo",
  "model": 22,
  "w": 1014,
  "h": 674,
  "ar": 1.5045,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "p22-2",
  "file": "img/p22-2.webp",
  "kind": "plan",
  "model": 22,
  "w": 4076,
  "h": 3072,
  "ar": 1.0736,
  "bbox": [
   0.1914,
   0.1195,
   0.8108,
   0.8851
  ],
  "transparent": true
 },
 {
  "slug": "p22-3",
  "file": "img/p22-3.webp",
  "kind": "render",
  "model": 22,
  "w": 2200,
  "h": 1646,
  "ar": 2.259,
  "bbox": [
   0.0764,
   0.3195,
   0.9292,
   0.8241
  ],
  "transparent": true
 },
 {
  "slug": "p22-4",
  "file": "img/p22-4.webp",
  "kind": "render",
  "model": 22,
  "w": 2200,
  "h": 1649,
  "ar": 1.534,
  "bbox": [
   0.0908,
   0.1902,
   0.905,
   0.8984
  ],
  "transparent": true
 },
 {
  "slug": "p22-5",
  "file": "img/p22-5.webp",
  "kind": "panel",
  "model": 22,
  "w": 2200,
  "h": 871,
  "ar": 5.1821,
  "bbox": [
   0.1025,
   0.2885,
   0.8855,
   0.6702
  ],
  "transparent": true
 },
 {
  "slug": "p22-6",
  "file": "img/p22-6.webp",
  "kind": "render",
  "model": 22,
  "w": 2200,
  "h": 1641,
  "ar": 2.3131,
  "bbox": [
   0.1023,
   0.2929,
   0.917,
   0.7651
  ],
  "transparent": true
 },
 {
  "slug": "p22-7",
  "file": "img/p22-7.webp",
  "kind": "panel",
  "model": 22,
  "w": 2200,
  "h": 1650,
  "ar": 5.373,
  "bbox": [
   0.1792,
   0.4079,
   0.8193,
   0.5667
  ],
  "transparent": true
 },
 {
  "slug": "p22-8",
  "file": "img/p22-8.webp",
  "kind": "panel",
  "model": 22,
  "w": 2200,
  "h": 872,
  "ar": 5.3556,
  "bbox": [
   0.0989,
   0.29,
   0.8818,
   0.6589
  ],
  "transparent": true
 },
 {
  "slug": "p22-9",
  "file": "img/p22-9.webp",
  "kind": "render",
  "model": 22,
  "w": 2200,
  "h": 1649,
  "ar": 1.5464,
  "bbox": [
   0.0972,
   0.1951,
   0.9172,
   0.9026
  ],
  "transparent": true
 },
 {
  "slug": "p32-1",
  "file": "img/p32-1.webp",
  "kind": "plan",
  "model": 32,
  "w": 4096,
  "h": 3072,
  "ar": 1.5413,
  "bbox": [
   0.0493,
   0.1133,
   0.9468,
   0.8896
  ],
  "transparent": true
 },
 {
  "slug": "p32-2",
  "file": "img/p32-2.webp",
  "kind": "render",
  "model": 32,
  "w": 2200,
  "h": 1643,
  "ar": 2.4124,
  "bbox": [
   0.0371,
   0.2867,
   0.9241,
   0.779
  ],
  "transparent": true
 },
 {
  "slug": "p32-3",
  "file": "img/p32-3.webp",
  "kind": "render",
  "model": 32,
  "w": 2200,
  "h": 1649,
  "ar": 1.6338,
  "bbox": [
   0.0208,
   0.1277,
   0.9622,
   0.8964
  ],
  "transparent": true
 },
 {
  "slug": "p32-4",
  "file": "img/p32-4.webp",
  "kind": "render",
  "model": 32,
  "w": 2048,
  "h": 1532,
  "ar": 2.4275,
  "bbox": [
   0.0654,
   0.2996,
   0.9722,
   0.799
  ],
  "transparent": true
 },
 {
  "slug": "p32-5",
  "file": "img/p32-5.webp",
  "kind": "panel",
  "model": 32,
  "w": 2200,
  "h": 1650,
  "ar": 7.5178,
  "bbox": [
   0.0415,
   0.4049,
   0.9592,
   0.5677
  ],
  "transparent": true
 },
 {
  "slug": "p32-6",
  "file": "img/p32-6.webp",
  "kind": "render",
  "model": 32,
  "w": 2200,
  "h": 1649,
  "ar": 1.6471,
  "bbox": [
   0.0259,
   0.1329,
   0.9753,
   0.902
  ],
  "transparent": true
 },
 {
  "slug": "p32-7",
  "file": "img/p32-7.webp",
  "kind": "photo",
  "model": 32,
  "w": 974,
  "h": 645,
  "ar": 1.5101,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-01-foh-club",
  "file": "img/wf-01-foh-club.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-02-community-hall",
  "file": "img/wf-02-community-hall.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-03-outdoor-event",
  "file": "img/wf-03-outdoor-event.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-04-tracking-to-laptop",
  "file": "img/wf-04-tracking-to-laptop.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-05-podcast-desk",
  "file": "img/wf-05-podcast-desk.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-06-control-booth",
  "file": "img/wf-06-control-booth.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-07-soundcheck-monitors",
  "file": "img/wf-07-soundcheck-monitors.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-08-project-studio",
  "file": "img/wf-08-project-studio.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-09-between-sets",
  "file": "img/wf-09-between-sets.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-10-teaching-room",
  "file": "img/wf-10-teaching-room.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-11-conference-panel",
  "file": "img/wf-11-conference-panel.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-12-streaming-the-room",
  "file": "img/wf-12-streaming-the-room.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-13-load-out",
  "file": "img/wf-13-load-out.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-14-black-box-theatre",
  "file": "img/wf-14-black-box-theatre.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-15-on-air-booth",
  "file": "img/wf-15-on-air-booth.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-16-two-desks",
  "file": "img/wf-16-two-desks.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-17-the-reception",
  "file": "img/wf-17-the-reception.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-18-overhead-mix-position",
  "file": "img/wf-18-overhead-mix-position.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-19-it-fits-the-table",
  "file": "img/wf-19-it-fits-the-table.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "wf-20-the-trolley",
  "file": "img/wf-20-the-trolley.jpg",
  "kind": "photo",
  "model": 0,
  "w": 2752,
  "h": 1536,
  "ar": 1.7917,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 }
];

export const CLIPS: Clip[] = [
 {
  "slug": "broll-01-knob-field",
  "file": "clip/broll-01-knob-field.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-02-hero-32",
  "file": "clip/broll-02-hero-32.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-03-profile-22",
  "file": "clip/broll-03-profile-22.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-04-ghost-preamps",
  "file": "clip/broll-04-ghost-preamps.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-05-plan-16",
  "file": "clip/broll-05-plan-16.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-06-lexicon",
  "file": "clip/broll-06-lexicon.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-07-ssm-metering",
  "file": "clip/broll-07-ssm-metering.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-08-usb-c",
  "file": "clip/broll-08-usb-c.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-09-compact-12",
  "file": "clip/broll-09-compact-12.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-10-live-foh",
  "file": "clip/broll-10-live-foh.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-11-room-daylight",
  "file": "clip/broll-11-room-daylight.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-12-family",
  "file": "clip/broll-12-family.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-13-band-room",
  "file": "clip/broll-13-band-room.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-14-two-players",
  "file": "clip/broll-14-two-players.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-15-reaching-back",
  "file": "clip/broll-15-reaching-back.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-16-plan-32",
  "file": "clip/broll-16-plan-32.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-17-plan-12",
  "file": "clip/broll-17-plan-12.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-18-rear-panel-32",
  "file": "clip/broll-18-rear-panel-32.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-19-aux-talkback",
  "file": "clip/broll-19-aux-talkback.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 },
 {
  "slug": "broll-20-hero-22",
  "file": "clip/broll-20-hero-22.mp4",
  "w": 2560,
  "h": 1440,
  "ar": 1.7778,
  "dur": 8.0
 }
];

/** Mean luminance of each named region, 0..1, measured on the plan. */
export const REGION_LUM: Record<string, number> = {
 "connectors": 0.2905,
 "phantom": 0.3919,
 "gain": 0.3545,
 "padHpf": 0.3443,
 "comp": 0.3386,
 "eq": 0.3808,
 "midSweep": 0.3854,
 "aux": 0.2802,
 "fxSend": 0.2744,
 "routing": 0.3141,
 "faders": 0.2405,
 "hiZ": 0.2736,
 "usbC": 0.2581,
 "qr": 0.334,
 "usbReturn": 0.2687,
 "outJacks": 0.4728,
 "outXlr": 0.4369,
 "monitor": 0.5578,
 "talkback": 0.2117,
 "lexicon": 0.4466,
 "meter": 0.2531,
 "auxMaster": 0.3651,
 "masterFader": 0.4698,
 "master": 0.3688
};
